[auth]
  cookie_name = "panelbase_jwt"
  jwt_expiration_hours = 24
  multi_user_enabled = true

[features]
  commands = false
  plugins = true

[server]
  host = "0.0.0.0"
  mode = "release"
  port = 23360
