[server]
ip    = "0.0.0.0"
port  = 2102
entry = "3VLRYq5iAJaP"
mode  = "release"

[auth]
jwt_secret = "yowNxSZf0fuzbgQRmjobXid6ptYh8bnb"
token_duration_minutes = 60

[functions]
plugins = false
commands = false
users = false
themes = false
